### ISSUE TITLE
Test nodes which do a full build should have a different build number than the Coherence one

### ISSUE THREAD

**Issue by kichalla** [aspnet/Coherence#208]
Following highlighted nodes actually do a full build (compile all repos + run tests)

![image](https://cloud.githubusercontent.com/assets/6559784/25948563/e7c01af2-3608-11e7-8eb1-522df0aed26c.png)

Having the same build number as Coherence (a dependency that a test node has) while helps in seeing that all these nodes are part of a set or chain, its problematic since when restoring packages for a repo (example: Options) during a build, it refers to local build artifacts feed + some other feeds (which includes ci-dev let's say). Now if a same build number is used as in Coherence, we don't know where the package was restored from, like it could be from local artifacts build or a Coherence build.

cc @pranavkm

**Comment by Eilon** [comment]
Hmm it seems like the bigger question is: why do any of the test builds compile the source of the product? Presumably the regular (Windows) build produces every artifact that is needed for every system.

@natemcmaster / @pranavkm - any idea why some test runs compile the product?

**Comment by pranavkm** [comment]
Since tests reference projects via project references (i.e. `<ProjectReference Include"..\..\src\SrcProj.csproj" />`), we'd have to do some cleverness to have it not recompile src. It was kinda easy to do this in project.json + global.json world by simply deleting the src directory. However, even this approach was riddled with exceptions for cases that required src projects to be present on disk (e.g. tests ../ including src files, steps in makefile.shade expecting a src directory to be present etc). 

If we do choose to go down this route again, we should attempt to make local tests follow the exact pattern (that is referencing packages and not sources). We spent a bunch of time in the past diagnosing issues because the CI was doing something very different from local builds. Consequently, local and individual project builds would succeed, but the CI test runs would fail inexplicably.

IMO, we are testing our product code and not necessarily our packages. If we didn't have a have two-phase build-test setup, we would have run build on each repo which is essentially what we get now. E2E pieces like MusicStore continue to be a way to verify the packaging and other post-processed outcomes of our builds.

**Comment by natemcmaster** [comment]
Hopefully we can address this in https://github.com/aspnet/Coherence-Signed/issues/648. It would be awesome to find a way to avoid rebuilding the product in order to run tests.

**Comment by Eilon** [comment]
I think perhaps even ideally we'd run tests on *signed* packages, no? We've long talked about at least changing the order of things, which at least would mean to turn tests in *parallel* with signing, but we could possibly even run it *after* signing, in which case we'd *have* to use package refs.
