### ISSUE TITLE
Harden nuget push to myget

### ISSUE THREAD

**Issue by muratg** [aspnet/Coherence#59]
If a package push fails, we end up having incoherent unusable packages.  I know we have a lot of retries per package, but sometimes we do end up failing pushing.

One idea is having an outer loop tracks that the packages that failed to push and retries those failed packages in the next iteration. If all packages are successfully pushed loop exits.  

We need to have the same logic in Coherence-signed as well.

**Comment by davidfowl** [comment]
We should also push in dependency order

**Comment by Eilon** [comment]
Actually, we talked about pushing in *reverse* dependency order, i.e. push MVC/EF first, and DI/Options last (you know what I mean). The reason for this is to ensure that trying to restore MVC would 100% fail if it's an incoherent upload because it's guaranteed to fail. If you push in dependency order (DI/Options first), you might get weird kinds of failures because some packages got upgraded but they might not work with each other.

Now, granted, it would mean that if there's an incoherent upload, everyone using `*` would be broken, so that's a downside of my proposed approach.

**Comment by pranavkm** [comment]
We actually do push to aspnetcidev in dependency order today (and to volatile too since it gets built in order). In terms of hardening - we have 10 retries for individual packages with delays between retries. We also avoid re-pushing packages (right now this is CoreCLR packages only) that have been uploaded. If there are networking issues that prevent us from publishing packages, no sane amount of hardening can help here.

**Comment by muratg** [comment]
@pranavkm Can't we make it better though?  Half uploads did hurt folks internally and externally.

**Comment by Eilon** [comment]
Do we still need this? Have we seen NuGet failures in a while? I figured the switch to dotnet.myget.org made things a lot better for us...

**Comment by pranavkm** [comment]
Actually no. It's super fast and way more reliable than www.myget.org. In fact, we could probably get rid of lot of the custom batching we wrote in KoreBuild \ Coherence \ Coherence-Signed etc and just do `nuget.exe push *.nupkg` since it's really fast.

**Comment by Eilon** [comment]
Easier to do nothing 😄
